/**
 * Constantes de países para selectores y formularios
 * Lista completa de países con códigos, nombres y datos útiles
 */

// Lista completa de países del mundo
export const COUNTRIES = [
  { code: 'AF', name: 'Afganistán', phoneCode: '+93', flag: '🇦🇫', continent: 'Asia' },
  { code: 'AL', name: 'Albania', phoneCode: '+355', flag: '🇦🇱', continent: 'Europa' },
  { code: 'DE', name: 'Alemania', phoneCode: '+49', flag: '🇩🇪', continent: 'Europa' },
  { code: 'AD', name: 'Andorra', phoneCode: '+376', flag: '🇦🇩', continent: 'Europa' },
  { code: 'AO', name: 'Angola', phoneCode: '+244', flag: '🇦🇴', continent: 'Africa' },
  { code: 'AQ', name: 'Antártida', phoneCode: '', flag: '🇦🇶', continent: 'Antártida' },
  { code: 'SA', name: 'Arabia Saudita', phoneCode: '+966', flag: '🇸🇦', continent: 'Asia' },
  { code: 'DZ', name: 'Argelia', phoneCode: '+213', flag: '🇩🇿', continent: 'Africa' },
  { code: 'AR', name: 'Argentina', phoneCode: '+54', flag: '🇦🇷', continent: 'América del Sur' },
  { code: 'AM', name: 'Armenia', phoneCode: '+374', flag: '🇦🇲', continent: 'Asia' },
  { code: 'AU', name: 'Australia', phoneCode: '+61', flag: '🇦🇺', continent: 'Oceanía' },
  { code: 'AT', name: 'Austria', phoneCode: '+43', flag: '🇦🇹', continent: 'Europa' },
  { code: 'AZ', name: 'Azerbaiyán', phoneCode: '+994', flag: '🇦🇿', continent: 'Asia' },
  { code: 'BS', name: 'Bahamas', phoneCode: '+1-242', flag: '🇧🇸', continent: 'América del Norte' },
  { code: 'BH', name: 'Baréin', phoneCode: '+973', flag: '🇧🇭', continent: 'Asia' },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880', flag: '🇧🇩', continent: 'Asia' },
  { code: 'BB', name: 'Barbados', phoneCode: '+1-246', flag: '🇧🇧', continent: 'América del Norte' },
  { code: 'BE', name: 'Bélgica', phoneCode: '+32', flag: '🇧🇪', continent: 'Europa' },
  { code: 'BZ', name: 'Belice', phoneCode: '+501', flag: '🇧🇿', continent: 'América del Norte' },
  { code: 'BJ', name: 'Benín', phoneCode: '+229', flag: '🇧🇯', continent: 'Africa' },
  { code: 'BT', name: 'Bután', phoneCode: '+975', flag: '🇧🇹', continent: 'Asia' },
  { code: 'BY', name: 'Bielorrusia', phoneCode: '+375', flag: '🇧🇾', continent: 'Europa' },
  { code: 'BO', name: 'Bolivia', phoneCode: '+591', flag: '🇧🇴', continent: 'América del Sur' },
  { code: 'BA', name: 'Bosnia y Herzegovina', phoneCode: '+387', flag: '🇧🇦', continent: 'Europa' },
  { code: 'BW', name: 'Botsuana', phoneCode: '+267', flag: '🇧🇼', continent: 'Africa' },
  { code: 'BR', name: 'Brasil', phoneCode: '+55', flag: '🇧🇷', continent: 'América del Sur' },
  { code: 'BN', name: 'Brunéi', phoneCode: '+673', flag: '🇧🇳', continent: 'Asia' },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359', flag: '🇧🇬', continent: 'Europa' },
  { code: 'BF', name: 'Burkina Faso', phoneCode: '+226', flag: '🇧🇫', continent: 'Africa' },
  { code: 'BI', name: 'Burundi', phoneCode: '+257', flag: '🇧🇮', continent: 'Africa' },
  { code: 'CV', name: 'Cabo Verde', phoneCode: '+238', flag: '🇨🇻', continent: 'Africa' },
  { code: 'KH', name: 'Camboya', phoneCode: '+855', flag: '🇰🇭', continent: 'Asia' },
  { code: 'CM', name: 'Camerún', phoneCode: '+237', flag: '🇨🇲', continent: 'Africa' },
  { code: 'CA', name: 'Canadá', phoneCode: '+1', flag: '🇨🇦', continent: 'América del Norte' },
  { code: 'QA', name: 'Catar', phoneCode: '+974', flag: '🇶🇦', continent: 'Asia' },
  { code: 'TD', name: 'Chad', phoneCode: '+235', flag: '🇹🇩', continent: 'Africa' },
  { code: 'CL', name: 'Chile', phoneCode: '+56', flag: '🇨🇱', continent: 'América del Sur' },
  { code: 'CN', name: 'China', phoneCode: '+86', flag: '🇨🇳', continent: 'Asia' },
  { code: 'CY', name: 'Chipre', phoneCode: '+357', flag: '🇨🇾', continent: 'Europa' },
  { code: 'CO', name: 'Colombia', phoneCode: '+57', flag: '🇨🇴', continent: 'América del Sur' },
  { code: 'KM', name: 'Comoras', phoneCode: '+269', flag: '🇰🇲', continent: 'Africa' },
  { code: 'CG', name: 'Congo', phoneCode: '+242', flag: '🇨🇬', continent: 'Africa' },
  { code: 'CD', name: 'Congo (Rep. Dem.)', phoneCode: '+243', flag: '🇨🇩', continent: 'Africa' },
  { code: 'KR', name: 'Corea del Sur', phoneCode: '+82', flag: '🇰🇷', continent: 'Asia' },
  { code: 'KP', name: 'Corea del Norte', phoneCode: '+850', flag: '🇰🇵', continent: 'Asia' },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506', flag: '🇨🇷', continent: 'América del Norte' },
  { code: 'CI', name: 'Costa de Marfil', phoneCode: '+225', flag: '🇨🇮', continent: 'Africa' },
  { code: 'HR', name: 'Croacia', phoneCode: '+385', flag: '🇭🇷', continent: 'Europa' },
  { code: 'CU', name: 'Cuba', phoneCode: '+53', flag: '🇨🇺', continent: 'América del Norte' },
  { code: 'DK', name: 'Dinamarca', phoneCode: '+45', flag: '🇩🇰', continent: 'Europa' },
  { code: 'DO', name: 'República Dominicana', phoneCode: '+1-809', flag: '🇩🇴', continent: 'América del Norte' },
  { code: 'EC', name: 'Ecuador', phoneCode: '+593', flag: '🇪🇨', continent: 'América del Sur' },
  { code: 'EG', name: 'Egipto', phoneCode: '+20', flag: '🇪🇬', continent: 'Africa' },
  { code: 'SV', name: 'El Salvador', phoneCode: '+503', flag: '🇸🇻', continent: 'América del Norte' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', phoneCode: '+971', flag: '🇦🇪', continent: 'Asia' },
  { code: 'ER', name: 'Eritrea', phoneCode: '+291', flag: '🇪🇷', continent: 'Africa' },
  { code: 'SK', name: 'Eslovaquia', phoneCode: '+421', flag: '🇸🇰', continent: 'Europa' },
  { code: 'SI', name: 'Eslovenia', phoneCode: '+386', flag: '🇸🇮', continent: 'Europa' },
  { code: 'ES', name: 'España', phoneCode: '+34', flag: '🇪🇸', continent: 'Europa' },
  { code: 'US', name: 'Estados Unidos', phoneCode: '+1', flag: '🇺🇸', continent: 'América del Norte' },
  { code: 'EE', name: 'Estonia', phoneCode: '+372', flag: '🇪🇪', continent: 'Europa' },
  { code: 'ET', name: 'Etiopía', phoneCode: '+251', flag: '🇪🇹', continent: 'Africa' },
  { code: 'PH', name: 'Filipinas', phoneCode: '+63', flag: '🇵🇭', continent: 'Asia' },
  { code: 'FI', name: 'Finlandia', phoneCode: '+358', flag: '🇫🇮', continent: 'Europa' },
  { code: 'FJ', name: 'Fiyi', phoneCode: '+679', flag: '🇫🇯', continent: 'Oceanía' },
  { code: 'FR', name: 'Francia', phoneCode: '+33', flag: '🇫🇷', continent: 'Europa' },
  { code: 'GA', name: 'Gabón', phoneCode: '+241', flag: '🇬🇦', continent: 'Africa' },
  { code: 'GM', name: 'Gambia', phoneCode: '+220', flag: '🇬🇲', continent: 'Africa' },
  { code: 'GE', name: 'Georgia', phoneCode: '+995', flag: '🇬🇪', continent: 'Asia' },
  { code: 'GH', name: 'Ghana', phoneCode: '+233', flag: '🇬🇭', continent: 'Africa' },
  { code: 'GI', name: 'Gibraltar', phoneCode: '+350', flag: '🇬🇮', continent: 'Europa' },
  { code: 'GR', name: 'Grecia', phoneCode: '+30', flag: '🇬🇷', continent: 'Europa' },
  { code: 'GD', name: 'Granada', phoneCode: '+1-473', flag: '🇬🇩', continent: 'América del Norte' },
  { code: 'GT', name: 'Guatemala', phoneCode: '+502', flag: '🇬🇹', continent: 'América del Norte' },
  { code: 'GY', name: 'Guyana', phoneCode: '+592', flag: '🇬🇾', continent: 'América del Sur' },
  { code: 'GN', name: 'Guinea', phoneCode: '+224', flag: '🇬🇳', continent: 'Africa' },
  { code: 'GW', name: 'Guinea-Bisáu', phoneCode: '+245', flag: '🇬🇼', continent: 'Africa' },
  { code: 'GQ', name: 'Guinea Ecuatorial', phoneCode: '+240', flag: '🇬🇶', continent: 'Africa' },
  { code: 'HT', name: 'Haití', phoneCode: '+509', flag: '🇭🇹', continent: 'América del Norte' },
  { code: 'HN', name: 'Honduras', phoneCode: '+504', flag: '🇭🇳', continent: 'América del Norte' },
  { code: 'HK', name: 'Hong Kong', phoneCode: '+852', flag: '🇭🇰', continent: 'Asia' },
  { code: 'HU', name: 'Hungría', phoneCode: '+36', flag: '🇭🇺', continent: 'Europa' },
  { code: 'IN', name: 'India', phoneCode: '+91', flag: '🇮🇳', continent: 'Asia' },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62', flag: '🇮🇩', continent: 'Asia' },
  { code: 'IR', name: 'Irán', phoneCode: '+98', flag: '🇮🇷', continent: 'Asia' },
  { code: 'IQ', name: 'Irak', phoneCode: '+964', flag: '🇮🇶', continent: 'Asia' },
  { code: 'IE', name: 'Irlanda', phoneCode: '+353', flag: '🇮🇪', continent: 'Europa' },
  { code: 'IS', name: 'Islandia', phoneCode: '+354', flag: '🇮🇸', continent: 'Europa' },
  { code: 'IL', name: 'Israel', phoneCode: '+972', flag: '🇮🇱', continent: 'Asia' },
  { code: 'IT', name: 'Italia', phoneCode: '+39', flag: '🇮🇹', continent: 'Europa' },
  { code: 'JM', name: 'Jamaica', phoneCode: '+1-876', flag: '🇯🇲', continent: 'América del Norte' },
  { code: 'JP', name: 'Japón', phoneCode: '+81', flag: '🇯🇵', continent: 'Asia' },
  { code: 'JO', name: 'Jordania', phoneCode: '+962', flag: '🇯🇴', continent: 'Asia' },
  { code: 'KZ', name: 'Kazajistán', phoneCode: '+7', flag: '🇰🇿', continent: 'Asia' },
  { code: 'KE', name: 'Kenia', phoneCode: '+254', flag: '🇰🇪', continent: 'Africa' },
  { code: 'KG', name: 'Kirguistán', phoneCode: '+996', flag: '🇰🇬', continent: 'Asia' },
  { code: 'KI', name: 'Kiribati', phoneCode: '+686', flag: '🇰🇮', continent: 'Oceanía' },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965', flag: '🇰🇼', continent: 'Asia' },
  { code: 'LA', name: 'Laos', phoneCode: '+856', flag: '🇱🇦', continent: 'Asia' },
  { code: 'LS', name: 'Lesoto', phoneCode: '+266', flag: '🇱🇸', continent: 'Africa' },
  { code: 'LV', name: 'Letonia', phoneCode: '+371', flag: '🇱🇻', continent: 'Europa' },
  { code: 'LB', name: 'Líbano', phoneCode: '+961', flag: '🇱🇧', continent: 'Asia' },
  { code: 'LR', name: 'Liberia', phoneCode: '+231', flag: '🇱🇷', continent: 'Africa' },
  { code: 'LY', name: 'Libia', phoneCode: '+218', flag: '🇱🇾', continent: 'Africa' },
  { code: 'LI', name: 'Liechtenstein', phoneCode: '+423', flag: '🇱🇮', continent: 'Europa' },
  { code: 'LT', name: 'Lituania', phoneCode: '+370', flag: '🇱🇹', continent: 'Europa' },
  { code: 'LU', name: 'Luxemburgo', phoneCode: '+352', flag: '🇱🇺', continent: 'Europa' },
  { code: 'MK', name: 'Macedonia del Norte', phoneCode: '+389', flag: '🇲🇰', continent: 'Europa' },
  { code: 'MG', name: 'Madagascar', phoneCode: '+261', flag: '🇲🇬', continent: 'Africa' },
  { code: 'MY', name: 'Malasia', phoneCode: '+60', flag: '🇲🇾', continent: 'Asia' },
  { code: 'MW', name: 'Malaui', phoneCode: '+265', flag: '🇲🇼', continent: 'Africa' },
  { code: 'MV', name: 'Maldivas', phoneCode: '+960', flag: '🇲🇻', continent: 'Asia' },
  { code: 'ML', name: 'Malí', phoneCode: '+223', flag: '🇲🇱', continent: 'Africa' },
  { code: 'MT', name: 'Malta', phoneCode: '+356', flag: '🇲🇹', continent: 'Europa' },
  { code: 'MA', name: 'Marruecos', phoneCode: '+212', flag: '🇲🇦', continent: 'Africa' },
  { code: 'MU', name: 'Mauricio', phoneCode: '+230', flag: '🇲🇺', continent: 'Africa' },
  { code: 'MR', name: 'Mauritania', phoneCode: '+222', flag: '🇲🇷', continent: 'Africa' },
  { code: 'MX', name: 'México', phoneCode: '+52', flag: '🇲🇽', continent: 'América del Norte' },
  { code: 'FM', name: 'Micronesia', phoneCode: '+691', flag: '🇫🇲', continent: 'Oceanía' },
  { code: 'MD', name: 'Moldavia', phoneCode: '+373', flag: '🇲🇩', continent: 'Europa' },
  { code: 'MC', name: 'Mónaco', phoneCode: '+377', flag: '🇲🇨', continent: 'Europa' },
  { code: 'MN', name: 'Mongolia', phoneCode: '+976', flag: '🇲🇳', continent: 'Asia' },
  { code: 'ME', name: 'Montenegro', phoneCode: '+382', flag: '🇲🇪', continent: 'Europa' },
  { code: 'MZ', name: 'Mozambique', phoneCode: '+258', flag: '🇲🇿', continent: 'Africa' },
  { code: 'MM', name: 'Myanmar', phoneCode: '+95', flag: '🇲🇲', continent: 'Asia' },
  { code: 'NA', name: 'Namibia', phoneCode: '+264', flag: '🇳🇦', continent: 'Africa' },
  { code: 'NR', name: 'Nauru', phoneCode: '+674', flag: '🇳🇷', continent: 'Oceanía' },
  { code: 'NP', name: 'Nepal', phoneCode: '+977', flag: '🇳🇵', continent: 'Asia' },
  { code: 'NI', name: 'Nicaragua', phoneCode: '+505', flag: '🇳🇮', continent: 'América del Norte' },
  { code: 'NE', name: 'Níger', phoneCode: '+227', flag: '🇳🇪', continent: 'Africa' },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234', flag: '🇳🇬', continent: 'Africa' },
  { code: 'NO', name: 'Noruega', phoneCode: '+47', flag: '🇳🇴', continent: 'Europa' },
  { code: 'NZ', name: 'Nueva Zelanda', phoneCode: '+64', flag: '🇳🇿', continent: 'Oceanía' },
  { code: 'OM', name: 'Omán', phoneCode: '+968', flag: '🇴🇲', continent: 'Asia' },
  { code: 'NL', name: 'Países Bajos', phoneCode: '+31', flag: '🇳🇱', continent: 'Europa' },
  { code: 'PK', name: 'Pakistán', phoneCode: '+92', flag: '🇵🇰', continent: 'Asia' },
  { code: 'PW', name: 'Palaos', phoneCode: '+680', flag: '🇵🇼', continent: 'Oceanía' },
  { code: 'PA', name: 'Panamá', phoneCode: '+507', flag: '🇵🇦', continent: 'América del Norte' },
  { code: 'PG', name: 'Papúa Nueva Guinea', phoneCode: '+675', flag: '🇵🇬', continent: 'Oceanía' },
  { code: 'PY', name: 'Paraguay', phoneCode: '+595', flag: '🇵🇾', continent: 'América del Sur' },
  { code: 'PE', name: 'Perú', phoneCode: '+51', flag: '🇵🇪', continent: 'América del Sur' },
  { code: 'PL', name: 'Polonia', phoneCode: '+48', flag: '🇵🇱', continent: 'Europa' },
  { code: 'PT', name: 'Portugal', phoneCode: '+351', flag: '🇵🇹', continent: 'Europa' },
  { code: 'GB', name: 'Reino Unido', phoneCode: '+44', flag: '🇬🇧', continent: 'Europa' },
  { code: 'CZ', name: 'República Checa', phoneCode: '+420', flag: '🇨🇿', continent: 'Europa' },
  { code: 'RO', name: 'Rumania', phoneCode: '+40', flag: '🇷🇴', continent: 'Europa' },
  { code: 'RU', name: 'Rusia', phoneCode: '+7', flag: '🇷🇺', continent: 'Europa' },
  { code: 'RW', name: 'Ruanda', phoneCode: '+250', flag: '🇷🇼', continent: 'Africa' },
  { code: 'KN', name: 'San Cristóbal y Nieves', phoneCode: '+1-869', flag: '🇰🇳', continent: 'América del Norte' },
  { code: 'SM', name: 'San Marino', phoneCode: '+378', flag: '🇸🇲', continent: 'Europa' },
  { code: 'VC', name: 'San Vicente y las Granadinas', phoneCode: '+1-784', flag: '🇻🇨', continent: 'América del Norte' },
  { code: 'LC', name: 'Santa Lucía', phoneCode: '+1-758', flag: '🇱🇨', continent: 'América del Norte' },
  { code: 'ST', name: 'Santo Tomé y Príncipe', phoneCode: '+239', flag: '🇸🇹', continent: 'Africa' },
  { code: 'SN', name: 'Senegal', phoneCode: '+221', flag: '🇸🇳', continent: 'Africa' },
  { code: 'RS', name: 'Serbia', phoneCode: '+381', flag: '🇷🇸', continent: 'Europa' },
  { code: 'SC', name: 'Seychelles', phoneCode: '+248', flag: '🇸🇨', continent: 'Africa' },
  { code: 'SG', name: 'Singapur', phoneCode: '+65', flag: '🇸🇬', continent: 'Asia' },
  { code: 'SY', name: 'Siria', phoneCode: '+963', flag: '🇸🇾', continent: 'Asia' },
  { code: 'SO', name: 'Somalia', phoneCode: '+252', flag: '🇸🇴', continent: 'Africa' },
  { code: 'LK', name: 'Sri Lanka', phoneCode: '+94', flag: '🇱🇰', continent: 'Asia' },
  { code: 'SZ', name: 'Suazilandia', phoneCode: '+268', flag: '🇸🇿', continent: 'Africa' },
  { code: 'ZA', name: 'Sudáfrica', phoneCode: '+27', flag: '🇿🇦', continent: 'Africa' },
  { code: 'SD', name: 'Sudán', phoneCode: '+249', flag: '🇸🇩', continent: 'Africa' },
  { code: 'SE', name: 'Suecia', phoneCode: '+46', flag: '🇸🇪', continent: 'Europa' },
  { code: 'CH', name: 'Suiza', phoneCode: '+41', flag: '🇨🇭', continent: 'Europa' },
  { code: 'SR', name: 'Surinam', phoneCode: '+597', flag: '🇸🇷', continent: 'América del Sur' },
  { code: 'TH', name: 'Tailandia', phoneCode: '+66', flag: '🇹🇭', continent: 'Asia' },
  { code: 'TZ', name: 'Tanzania', phoneCode: '+255', flag: '🇹🇿', continent: 'Africa' },
  { code: 'TJ', name: 'Tayikistán', phoneCode: '+992', flag: '🇹🇯', continent: 'Asia' },
  { code: 'TL', name: 'Timor Oriental', phoneCode: '+670', flag: '🇹🇱', continent: 'Asia' },
  { code: 'TG', name: 'Togo', phoneCode: '+228', flag: '🇹🇬', continent: 'Africa' },
  { code: 'TO', name: 'Tonga', phoneCode: '+676', flag: '🇹🇴', continent: 'Oceanía' },
  { code: 'TT', name: 'Trinidad y Tobago', phoneCode: '+1-868', flag: '🇹🇹', continent: 'América del Norte' },
  { code: 'TN', name: 'Túnez', phoneCode: '+216', flag: '🇹🇳', continent: 'Africa' },
  { code: 'TM', name: 'Turkmenistán', phoneCode: '+993', flag: '🇹🇲', continent: 'Asia' },
  { code: 'TR', name: 'Turquía', phoneCode: '+90', flag: '🇹🇷', continent: 'Asia' },
  { code: 'TV', name: 'Tuvalu', phoneCode: '+688', flag: '🇹🇻', continent: 'Oceanía' },
  { code: 'UA', name: 'Ucrania', phoneCode: '+380', flag: '🇺🇦', continent: 'Europa' },
  { code: 'UG', name: 'Uganda', phoneCode: '+256', flag: '🇺🇬', continent: 'Africa' },
  { code: 'UY', name: 'Uruguay', phoneCode: '+598', flag: '🇺🇾', continent: 'América del Sur' },
  { code: 'UZ', name: 'Uzbekistán', phoneCode: '+998', flag: '🇺🇿', continent: 'Asia' },
  { code: 'VU', name: 'Vanuatu', phoneCode: '+678', flag: '🇻🇺', continent: 'Oceanía' },
  { code: 'VE', name: 'Venezuela', phoneCode: '+58', flag: '🇻🇪', continent: 'América del Sur' },
  { code: 'VN', name: 'Vietnam', phoneCode: '+84', flag: '🇻🇳', continent: 'Asia' },
  { code: 'YE', name: 'Yemen', phoneCode: '+967', flag: '🇾🇪', continent: 'Asia' },
  { code: 'DJ', name: 'Yibuti', phoneCode: '+253', flag: '🇩🇯', continent: 'Africa' },
  { code: 'ZM', name: 'Zambia', phoneCode: '+260', flag: '🇿🇲', continent: 'Africa' },
  { code: 'ZW', name: 'Zimbabue', phoneCode: '+263', flag: '🇿🇼', continent: 'Africa' }
];

// Función para obtener país por código
export const getCountryByCode = (code) => {
  return COUNTRIES.find(country => country.code === code.toUpperCase()) || null;
};

// Función para buscar países por nombre
export const searchCountries = (searchTerm) => {
  if (!searchTerm) return COUNTRIES;
  
  const term = searchTerm.toLowerCase();
  return COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(term) ||
    country.code.toLowerCase().includes(term)
  );
};

// Función para obtener países por continente
export const getCountriesByContinent = (continent) => {
  return COUNTRIES.filter(country => country.continent === continent);
};

// Lista de continentes
export const CONTINENTS = [
  'África',
  'América del Norte', 
  'América del Sur',
  'Asia',
  'Europa',
  'Oceanía',
  'Antártida'
];

// Países populares (para opciones rápidas)
export const POPULAR_COUNTRIES = [
  'MX', 'US', 'CA', 'ES', 'AR', 'CO', 'CL', 'PE', 'VE', 'EC',
  'BR', 'GB', 'FR', 'DE', 'IT', 'PT', 'AU', 'JP', 'CN', 'IN'
];

// Exportar todo
export default {
  COUNTRIES,
  CONTINENTS,
  POPULAR_COUNTRIES,
  getCountryByCode,
  searchCountries,
  getCountriesByContinent
};
